'use strict';

const _ = require('lodash');
const axios = require('axios');
const cheerio = require('cheerio');

module.exports = {
  name: 'kingjamesprogramming',
  aliases: ['kingjames', 'bible'],
  guildOnly: true,
  description: 'Posts generated by a Markov chain trained on the King James Bible, Structure and Interpretation of Computer Programs, and some of Eric S. Raymond\'s writings. https://kingjamesprogramming.tumblr.com',
  requiredChannelPermissions: ['SEND_MESSAGES'],
  async execute({message}) {
    const result = await axios.get('https://kingjamesprogramming.tumblr.com/random');
    const $ = cheerio.load(_.get(result, 'data'));
    $('code').each(function() {
      $(this).replaceWith('`' + $(this).text() + '`');
    });
    $('b, strong').each(function() {
      $(this).replaceWith('**' + $(this).text() + '**');
    });
    $('i, em').each(function() {
      $(this).replaceWith('*' + $(this).text() + '*');
    });
    await message.channel.send($('article blockquote').text());
  },
};
